name: Run Unit Tests

# Runs on pushes to pull request
on: pull_request

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependency
        run: npm install
      - name: Run tests
        run: npm test
